-- MySQL Script generated by MySQL Workbench
-- Fri Apr  7 15:27:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema businessonline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema businessonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `businessonline` DEFAULT CHARACTER SET latin1 ;
USE `businessonline` ;

-- -----------------------------------------------------
-- Table `businessonline`.`Manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessonline`.`Manufacturer` (
  `ManufacturerID` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Country` VARCHAR(15) NULL DEFAULT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `Phone` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`ManufacturerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Thông tin nhà sản xuất của sản phẩm';


-- -----------------------------------------------------
-- Table `businessonline`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessonline`.`Category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT COMMENT 'auto increment\n\nBegin = 1',
  `CategoryName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '100 char',
  `Description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `ParentID` INT NOT NULL DEFAULT 0 COMMENT 'Category parent id\n\ndefault 0',
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1
COMMENT = 'Danh sách các danh mục sản phẩm'
PACK_KEYS = Default
ROW_FORMAT = Default;


-- -----------------------------------------------------
-- Table `businessonline`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessonline`.`Product` (
  `ProductID` INT NOT NULL COMMENT 'Primary key for Product rows.',
  `Name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Name of the product\n',
  `MakeFlag` BIT(1) NOT NULL COMMENT '0 = Product is purchased.\n\n1 = Product is manufactured in-house.',
  `Price` DOUBLE NOT NULL,
  `Description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `Status` VARCHAR(4) NOT NULL,
  `Discount` TINYINT(1) NOT NULL,
  `Picture` BINARY(255) NULL DEFAULT NULL,
  `ManufacturerID` VARCHAR(10) NOT NULL,
  `CategoryID` INT NOT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `PRODUCT_SUPPLIER` (`ManufacturerID` ASC),
  INDEX `fk_Product_ProductCategory1_idx` (`CategoryID` ASC),
  CONSTRAINT `PRODUCT_SUPPLIER`
    FOREIGN KEY (`ManufacturerID`)
    REFERENCES `businessonline`.`Manufacturer` (`ManufacturerID`),
  CONSTRAINT `fk_Product_ProductCategory1`
    FOREIGN KEY (`CategoryID`)
    REFERENCES `businessonline`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Thông tin của một sản phẩm';


-- -----------------------------------------------------
-- Table `businessonline`.`StoreCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessonline`.`StoreCategory` (
  `StoreCategoryID` VARCHAR(10) NOT NULL,
  `StoreCategoryName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`StoreCategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Danh sách các loại store ';


-- -----------------------------------------------------
-- Table `businessonline`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessonline`.`Store` (
  `StoreID` VARCHAR(10) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `Phone` VARCHAR(24) NOT NULL,
  `Longitude` DOUBLE(10,4) NOT NULL,
  `Latitude` DOUBLE(10,4) NOT NULL,
  `Email` VARCHAR(30) NULL DEFAULT NULL,
  `OpeningTime` DATE NOT NULL,
  `ClosingTime` DATE NOT NULL,
  `Rating` INT(11) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `StoreCategoryID` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`StoreID`),
  INDEX `STORE_STORECATEGORIES` (`StoreCategoryID` ASC),
  CONSTRAINT `STORE_STORECATEGORIES`
    FOREIGN KEY (`StoreCategoryID`)
    REFERENCES `businessonline`.`StoreCategory` (`StoreCategoryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Thông tin cửa hàng (STORE) đăng kí bussiness online.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
