theme: jekyll-theme-cayman
name: services-around-me
description: services for searching, bussiness online
url: https://hnhatr.github.io
baseurl: /services-around-me
paginate: 5
timezone: America/Los_Angeles
defaults:
- scope:
    path: blog
    type: pages
  values:
    layout: post
    sectionid: blog
- scope:
    path: docs
    type: pages
  values:
    layout: docs
    sectionid: docs
- scope:
    path: community
    type: pages
  values:
    layout: default
    sectionid: community
- scope:
    path: versions
    type: pages
  values:
    layout: default
    sectionid: versions
exclude:
- Gemfile
- README.md
gems:
- jekyll-redirect-from
- jekyll-paginate
